// Ideally, this file would be written in typescript as well but something is
// not working correctly. So for now at least this will be plain javascript.

// The next two functions `registerProgress` and `reportProgress` will be
// called from the rust wasm module. They have to be defined before importing
// the wasm module otherwise the import will fail.

// We just forward the data to the main thread. The main thread will add the
// gif to the progress module.
self.registerProgress = (id, name, numberOfFrames) => {
    self.postMessage({
        type: 'register_progress',
        id,
        name,
        numberOfFrames
    });
}

// This function will be called after every frame that was processed by the
// wasm module. All we do here is pass the information through to the main
// thread which will then update the progress bar.
self.reportProgress = (id, currentFrame) => {
    self.postMessage({
        type: 'report_progress',
        id,
        currentFrame
    });
}

// Import the wasm wrapper module generated by wasm-bindgen.
require("../pkg/gif");

// This does not really load the wasm module. This in fact is loaded through
// the webpack file-loader. This loader will copy the wasm file to the output
// folder and this require only gives us the path to the wasm module which can
// then be passd to the init function of the wasm_bindgen wrapper.
const wasmPath = require('../pkg/gif_bg.wasm');

// Initialize the wasm module. We get back a promise that resolves once the
// wasm module was successfully initialized.
const gifModule = self.wasm_bindgen(wasmPath);

// Once we get a message from the main thread we can start processing the gif.
self.addEventListener('message', async (event) => {
  const { id, name, buffer } = event.data;

  // Make sure the wasm module is fully initialized.
  await gifModule;
  const gif = self.wasm_bindgen;

  // Reverse the gif.
  const reversedBuffer = gif.reverse_gif(id, name, buffer);

  // Tell the main thread that we're finished.
  self.postMessage({
      type: 'finished',
      id,
      name,
      buffer,
      reversedBuffer
  });
});